<!DOCTYPE html>
<html class="no-js" lang="en">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>软件测试/测试开发丨Python 错误与异常 - IT学习者博客</title>
	<script>(function(d,e){d[e]=d[e].replace("no-js","js");})(document.documentElement,"className");</script>
	<meta name="description" content="">
		<meta property="og:title" content="软件测试/测试开发丨Python 错误与异常" />
<meta property="og:description" content="python 错误与异常 语法错误与定位 错误 语法错误逻辑错误系统错误 # 错误 # 语法错误 num = 1 if num &gt; 1 # 缺少冒号 print(&#34;num&gt;1&#34;) # 结构是： SyntaxError: expected &#39;:&#39; line 4第四行 # 逻辑错误 if num &gt;=1: print(&#34;num&lt;=1&#34;) # 实现结果与实际场景逻辑不对 elif num&gt;100: print(&#34;num&lt;100&#34;) # 实现结果与实际场景逻辑不对 # 系统错误 # 如运行是内存泄露、系统错误等引起的运行失败 异常 程序执行过程中出现的未知错误语法和逻辑都是正常的程序业务逻辑不完善引起的程序漏洞–bug 错误与异常的区别 异常可以被捕获和处理错误一般是编码错误、逻辑错误、系统错误 常见的异常类型 异常类型：docs.python.org/3/library/e…常见的异常类型
** 除零类型、名称异常、索引异常、键异常、值异常、属性异常等 # 除零异常 def div(a,b): return a/b print(div(1, 0)) # 异常是：ZeroDivisionError: division by zero # 名称异常 # num =1 if numb &gt;1: num =2 # 异常是：NameError: name &#39;numb&#39; is not defined." />
<meta property="og:type" content="article" />
<meta property="og:url" content="https://itnewbiea.github.io/posts/5679554ca62fa6bad6793f700657dd97/" /><meta property="article:section" content="posts" />
<meta property="article:published_time" content="2024-01-02T20:00:00+08:00" />
<meta property="article:modified_time" content="2024-01-02T20:00:00+08:00" />


	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
	<link rel="dns-prefetch" href="//fonts.googleapis.com">
	<link rel="dns-prefetch" href="//fonts.gstatic.com">
	<link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700">

	<link rel="stylesheet" href="/css/style.css">
	

	<link rel="shortcut icon" href="/favicon.ico">
		
</head>
<body class="body">
	<div class="container container--outer">
		<header class="header">
	<div class="container header__container">
		
	<div class="logo">
		<a class="logo__link" href="/" title="IT学习者博客" rel="home">
			<div class="logo__item logo__text">
					<div class="logo__title">IT学习者博客</div>
					
				</div>
		</a>
	</div>
		<div class="divider"></div>
	</div>
</header>
		<div class="wrapper flex">
			<div class="primary">
			
<main class="main" role="main">
	<article class="post">
		<header class="post__header">
			<h1 class="post__title">软件测试/测试开发丨Python 错误与异常</h1>
			
		</header>
		<div class="content post__content clearfix">
			
<div id="content_views" class="htmledit_views">
                    <h2><img alt="" src="https://images2.imgbox.com/01/13/QSQkyPaw_o.jpg"></h2> 
<h2>python 错误与异常</h2> 
<h3>语法错误与定位</h3> 
<h4>错误</h4> 
<ul><li>语法错误</li><li>逻辑错误</li><li>系统错误</li></ul> 
<pre><code class="language-python"># 错误
# 语法错误
num = 1
if num &gt; 1 # 缺少冒号
    print("num&gt;1")  # 结构是： SyntaxError: expected ':'  line 4第四行
# 逻辑错误
if num &gt;=1:
    print("num&lt;=1")  # 实现结果与实际场景逻辑不对
elif num&gt;100:
    print("num&lt;100")  # 实现结果与实际场景逻辑不对
# 系统错误
# 如运行是内存泄露、系统错误等引起的运行失败

</code></pre> 
<h4>异常</h4> 
<ul><li>程序执行过程中出现的未知错误</li><li>语法和逻辑都是正常的</li><li>程序业务逻辑不完善引起的程序漏洞–bug</li></ul> 
<h4>错误与异常的区别</h4> 
<ul><li>异常可以被捕获和处理</li><li>错误一般是编码错误、逻辑错误、系统错误</li></ul> 
<h4>常见的异常类型</h4> 
<ul><li>异常类型：<a href="https://link.juejin.cn?target=https%3A%2F%2Fdocs.python.org%2F3%2Flibrary%2Fexceptions.html%23bltin-exceptions" rel="nofollow" title="docs.python.org/3/library/e…">docs.python.org/3/library/e…</a></li><li>常见的异常类型<br> ** 除零类型、名称异常、索引异常、键异常、值异常、属性异常等</li></ul> 
<pre><code class="language-python"># 除零异常
def div(a,b):
    return a/b
print(div(1, 0)) # 异常是：ZeroDivisionError: division by zero
# 名称异常
# num =1
if numb &gt;1:
    num =2  # 异常是：NameError: name 'numb' is not defined. Did you mean: 'num'?
# 索引异常
list = [1,2,3]
print(list[4]) # 异常是：ZeroDivisionError: division by zero
# 键异常
dict1 = {"name":"wlll","age":18}
print(dict1['sex']) # 异常是：KeyError: 'sex'
# 值异常
a = input("请输入一个值：")
print(int(a)) # 输入不是数字后，异常是：ValueError: invalid literal for int() with base 10: 'a'
# 属性异常
# 更新一些常量属性时会抛出的异常
</code></pre> 
<h4>异常/错误处理流程</h4> 
<p></p> 
<p class="img-center"><a href="https://link.juejin.cn?target=https%3A%2F%2Fceshiren.com%2Fuploads%2Fdefault%2Foriginal%2F3X%2F4%2F3%2F439e63e41af613e6d19c0a4680ee6cb1e8474e79.jpeg" rel="nofollow"><img alt="image" height="142" src="https://images2.imgbox.com/c0/d8/g0e6cq0A_o.png" width="800"></a></p> 
<p><a href="https://link.juejin.cn?target=https%3A%2F%2Fceshiren.com%2Fuploads%2Fdefault%2Foriginal%2F3X%2F4%2F3%2F439e63e41af613e6d19c0a4680ee6cb1e8474e79.jpeg" rel="nofollow" title="image1310×233 40.6 KB">image1310×233 40.6 KB</a></p> 
<ul><li>如果是拼写、配置等引起的错误，根据出错信息排查出现的位置进行解决</li><li>如果是程序设计不完善引起的漏洞，根据漏洞的情况进行设计处理漏洞的逻辑</li></ul> 
<h3>异常捕获、异常处理</h3> 
<p></p> 
<p class="img-center"><img alt="image" height="629" src="https://images2.imgbox.com/c9/73/evy2wgCC_o.png" width="729"></p> 
<pre><code class="language-python">def div(a, b):
    return a % b
try:
    print(div(1, 1))  # 正确显示0
except Exception as e:
    print('此处有异常', e) # 没有异常不显示,有异常显示异常
else:
    print("哈哈,没有异常") # 没有异常则打印
finally:  # 无论是否有异常后还会执行此处
    print('finally') # 结果是 finally
</code></pre> 
<h4>使用raise抛出异常</h4> 
<ul><li>使用raise 触发异常并使用exception</li></ul> 
<pre><code class="language-python">def aum(num):
    if num &lt;=0 or num &gt;=100:
        raise ValueError(f"值错误:{num}")
    else:
        print(f"设置的年龄为:{num}")
print(aum(-1)) # 主动抛出异常:ValueError: 值错误:-1
print(aum(80)) # 结果是: 设置的年龄为:80
</code></pre> 
<h3>自定义异常</h3> 
<ul><li>自己继承错误类或方法自己写一个异常定义</li><li>class MyError(Exception):</li></ul> 
<pre><code class="language-python">def __init__(self, value):
</code></pre> 
<pre><code class="language-python">    self.value = value
</code></pre> 
<pre><code class="language-python">def __str__(self):
</code></pre> 
<pre><code class="language-python">    return repr(self.value)
</code></pre> 
<pre><code class="language-python">class MyException(Exception):
    def __init__(self, value):
        self.value = value
        print(f'这是一个异常:{value}')
    def __str__(self):
        return repr(self.value)

def aum(num):
    if num &lt;=0 or num &gt;=100:
        raise MyException(f"值错误:{num}")
    else:
        print(f"设置的年龄为:{num}")
aum(-55) # 异常抛出:MyException: '值错误:-55'
</code></pre> 
<p><strong>最后感谢每一个认真阅读我文章的人，礼尚往来总是要有的，虽然不是什么很值钱的东西，如果你用得到的话可以直接拿走：</strong></p> 
<h4><img alt="" height="707" src="https://images2.imgbox.com/ba/de/614PbLWz_o.png" width="929"></h4> 
<p>这些资料，对于【软件测试】的朋友来说应该是最全面最完整的备战仓库，这个仓库也陪伴上万个测试工程师们走过最艰难的路程，希望也能帮助到你！ </p> 
<p class="img-center"><img alt="" height="126" src="https://images2.imgbox.com/97/2b/j7GJ6YCX_o.png" width="634"></p>
                </div>
		</div>
	</article>
</main>


<nav class="pager flex">
	<div class="pager__item pager__item--prev">
		<a class="pager__link" href="/posts/a35fde871d721b9c4c929e286cbfd491/" rel="prev">
			<span class="pager__subtitle">«&thinsp;Previous</span>
			<p class="pager__title">opencv期末练习题（6）附带解析</p>
		</a>
	</div>
	<div class="pager__item pager__item--next">
		<a class="pager__link" href="/posts/a86bb7d4fb777e0a583f6b1c2c2f9406/" rel="next">
			<span class="pager__subtitle">Next&thinsp;»</span>
			<p class="pager__title">软件测试/测试开发丨Pytest结合数据驱动</p>
		</a>
	</div>
</nav>


			</div>
			
		</div>
		<footer class="footer">
	<div class="container footer__container flex">
		
		<div class="footer__copyright">
			&copy; 2024 IT学习者博客.
			<span class="footer__copyright-credits">Generated with <a href="https://gohugo.io/" rel="nofollow noopener" target="_blank">Hugo</a> and <a href="https://github.com/Vimux/Mainroad/" rel="nofollow noopener" target="_blank">Mainroad</a> theme.</span>
		</div>
	</div>
</footer>
<script src="https://itnewbiea.github.io/js/foot.js"></script>


	</div>
<script async defer src="/js/menu.js"></script>
</body>
</html>